language: go

branches:
  only:
  - master

go:
  - "1.x" # use the latest Go release

env:
  - GO111MODULE=on

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.18.0

script:
  - golangci-lint run ./...
  - make
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_PULL_REQUEST
  - build/release-travis
